# @package _global_
defaults:
  - _self_
  - iris: iris

experiment: run_with_atariari

# experiment args
output_dir: ${join_path:${hydra:sweep.dir},${hydra:sweep.subdir}}
checkpoint_dir: ${join_path:${base_output_dir},checkpoints}
checkpoint_file: Breakout # Change if reqd (Checkpoint for iris encoder)
seed: 0
device: cuda
encoder: "iris" # Change if reqd

# data parameters
data_overlay: ""
env_name: "BreakoutNoFrameskip-v4" # Change if reqd
steps: 500 #50000
collect_mode: "random_agent" # "random_agent" or "pretrained_ppo_color" 
color: True # Always set to True
min_episode_length: 64


iris:
  env:
    train: 
      id: ${env_name}